language: ruby
rvm:
  - 2.5.3
script:
#- bundle exec /usr/bin/env RAILS_ENV=test rake db:drop
- bundle exec /usr/bin/env RAILS_ENV=test rake db:create
- bundle exec /usr/bin/env RAILS_ENV=test rake db:schema:load
- bundle exec /usr/bin/env RAILS_ENV=test rake db:migrate
- bundle exec /usr/bin/env RAILS_ENV=test rake db:seed
- bundle exec rspec spec