language: ruby
rvm:
  - 2.5.3

before_script:
- pwd
- ls -a
#- mv config/database.yml.travis config/database.yml
#- mv config/local_env.yml.travis config/local_env.yml
###############################################################
## Done because travis stopped playing nice with postgis
## From: https://github.com/travis-ci/travis-ci/issues/7048
## Maybe remove these 4 lines eventually.
#- sudo apt-get update
#- sudo apt-get autoremove postgis*
#- sudo apt-get autoremove postgresql*
#- sudo apt-get install postgresql-9.3-postgis-2.1
###############################################################

#- psql -U postgres -c "create extension postgis"

script:
#- bundle exec /usr/bin/env RAILS_ENV=test rake db:drop
- bundle exec /usr/bin/env RAILS_ENV=test rake db:create
- bundle exec /usr/bin/env RAILS_ENV=test rake db:schema:load
- bundle exec /usr/bin/env RAILS_ENV=test rake db:migrate
- bundle exec /usr/bin/env RAILS_ENV=test rake db:seed
- bundle exec rspec spec